### ISSUE TITLE
newbie here...Trying to install kerastuneR produce an error

### ISSUE THREAD

**Issue by airyadriana** [EagerAI/kerastuneR#40]
Hi all,
I installed reticulate, keras, miniconda, and tensorflow from these instructions (https://hastie.su.domains/ISLR2/keras-instructions.html). Now, I am trying to install kerastuneR and I followed the dev version installation

devtools::install_github('EagerAI/kerastuneR')
kerastuneR::install_kerastuner(python_path = "/Users/airy/islr-miniconda/envs/r-reticulate/bin/python")

but, it produces this error:
> kerastuneR::install_kerastuner(python_path = "/Users/airy/islr-miniconda/envs/r-reticulate/bin/python")
Activated conda python: /Users/airy/islr-miniconda/envs/r-reticulate/bin/python
ERROR: Invalid requirement: 'keras-tuner==1.1.0 pydot'
Error: Error installing package(s): "'keras-tuner==1.1.0 pydot'"

**Am I using the wrong path?**

my py_config() is this:
R reticulate configuration
python:         /Users/airy/islr-miniconda/envs/r-reticulate/bin/python
libpython:      /Users/airy/islr-miniconda/envs/r-reticulate/lib/libpython3.9.dylib
pythonhome:     /Users/airy/islr-miniconda/envs/r-reticulate:/Users/airy/islr-miniconda/envs/r-reticulate
version:        3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35)  [Clang 11.1.0 ]
numpy:          /Users/airy/islr-miniconda/envs/r-reticulate/lib/python3.9/site-packages/numpy
numpy_version:  1.19.5
R, Python tensorflow version: 2.8.0, 2.4.1
Python numpy version: 1.19.5
Python scipy version: 1.7.0
Python pillow version: 8.2.0

**Comment by turgut090** [comment]
Hi there. There was a breaking change in reticulate pkg. I will fix it in 24 hours and let you know.

**Comment by turgut090** [comment]
@airyadriana Hi, could you reinstall the development version of kerastuneR?

```
devtools::install_github('eagerai/kerastuneR')
```

If it fails again, please reopen this issue.

**Comment by airyadriana** [comment]
It worked. Thanks!
