### ISSUE TITLE
Issue with installation 

### ISSUE THREAD

**Issue by HashkiFMI** [EagerAI/kerastuneR#47]
Dear turgut090, the author of keratuneR, 
I have issues with installing kerastuneR. I have tesnorflow and keras installed and work in my RStudio without any issues. 
I am using the tutorial in this link for installation:
https://github.com/EagerAI/kerastuneR 
When I want to install kerastuneR, installation doesn't give error but loading that with library("kerastuneR") or running this command:
```kerastuneR::install_kerastuner()```
gives this error:
```Error: package or namespace load failed for ‘kerastuneR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/magick/libs/magick.so':
  libMagick++-6.Q16.so.8: cannot open shared object file: No such file or directory
```
But this file is exist in this path:
```/usr/local/lib/R/site-library/magick/libs/magick.so```

So i don't know how to solve the issue and what is cause of the error. I will be thankful if you advise me and help to be able to install and use your package.

Thanks,
Haleh

**Comment by turgut090** [comment]
Hello, could install the following first and see if everything works fine:
```
install.packages('magick')
```
